<template>
  <div v-if="loader">
    <div class="loader">
      <div class="loader-overlay d-flex align-items-center justify-content-center" >
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style=" margin: auto; background: none; display: block; shape-rendering: auto; " width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" > <rect x="17.5" y="30" width="15" height="40" fill="#f1f2ff"> <animate attributeName="y" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.5;1" values="18;30;30" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.2s" ></animate> <animate attributeName="height" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.5;1" values="64;40;40" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.2s" ></animate> </rect> <rect x="42.5" y="30" width="15" height="40" fill="#e6e8ff"> <animate attributeName="y" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.5;1" values="20.999999999999996;30;30" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.1s" ></animate> <animate attributeName="height" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.5;1" values="58.00000000000001;40;40" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.1s" ></animate> </rect> <rect x="67.5" y="30" width="15" height="40" fill="#c8d6ff"> <animate attributeName="y" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.5;1" values="20.999999999999996;30;30" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" ></animate> <animate attributeName="height" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.5;1" values="58.00000000000001;40;40" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" ></animate> </rect> <!-- [ldio] generated by https://loading.io/ --> </svg>
          <div>
            <h3>Processing your action</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import EventBus from '../eventBus.js';
export default {
  // props:['loading'],
  data(){
    return{
      authenticated: null,
      user: null,
      token: null,
      loader: false,
    }
  },
  created() {
    // EventBus.$on('loaderOverlay', (val) => {
    //     this.loading = val;
    //   })
  },
  watch: {
    '$store.state.authenticated': function() {
      // console.log(this.$store.getters['getLoader']);
      this.authenticated = this.$store.getters['authenticated'];
    },
    '$store.state.user': function() {
      // console.log(this.$store.getters['getLoader']);
      this.user = this.$store.getters['authenticated'];
    },
    '$store.state.token': function() {
      // console.log(this.$store.getters['getLoader']);
      this.token = this.$store.getters['authenticated'];
    }
  },
  
  methods: {

  }
};
</script>

<style>
.loader {
  position: fixed;
  z-index: 2;
  top: 0;
  left: 0;
  background: rgba(255, 255, 255, 0.7);
  height: 100vh;
  width: 100vw;
}
.loader-overlay {
  height: 100%;
  width: 100%;
}
</style>