<template>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card square">
          <div class="card-header">Add Note</div>
          <div class="card-body">

            <form action="#" method="post" @submit.prevent="store">
              <div class="form-group">
                <label for="title">Title</label>
                <input type="text" v-model="form.title" id="title" class="form-control square" />
                <div v-if="theErrors.title" class="text-danger mt-2">
                  {{ theErrors.title[0] }}
                </div>
              </div>

              <div class="form-group">
                <label for="subject">Subject</label>
                <select v-model="form.subject" id="subject" class="form-control square" >
                  <option value="" disabled>Choose subject...</option>
                  <option v-for="subject in subjects" :key="subject.id" :value="subject.id" >
                    {{ subject.name }}
                  </option>
                </select>
                <div v-if="theErrors.subject" class="text-danger mt-2">
                  {{ theErrors.subject[0] }}
                </div>
              </div>

              <div class="form-group">
                <label for="description">Description</label>
                <textarea type="text" v-model="form.description" id="description" rows="5" class="form-control square" ></textarea>
                <div v-if="theErrors.description" class="text-danger mt-2">
                  {{ theErrors.description[0] }}
                </div>
              </div>

              <button type="submit" class="btn btn-primary square d-flex align-items-center">
                Create
                <template v-if="loading">
                  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="20px" height="20px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid"> <rect x="17.5" y="30" width="15" height="40" fill="#f1f2ff"> <animate attributeName="y" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.5;1" values="18;30;30" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.2s"></animate> <animate attributeName="height" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.5;1" values="64;40;40" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.2s"></animate> </rect> <rect x="42.5" y="30" width="15" height="40" fill="#e6e8ff"> <animate attributeName="y" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.5;1" values="20.999999999999996;30;30" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.1s"></animate> <animate attributeName="height" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.5;1" values="58.00000000000001;40;40" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.1s"></animate> </rect> <rect x="67.5" y="30" width="15" height="40" fill="#c8d6ff"> <animate attributeName="y" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.5;1" values="20.999999999999996;30;30" keySplines="0 0.5 0.5 1;0 0.5 0.5 1"></animate> <animate attributeName="height" repeatCount="indefinite" dur="1s" calcMode="spline" keyTimes="0;0.5;1" values="58.00000000000001;40;40" keySplines="0 0.5 0.5 1;0 0.5 0.5 1"></animate> </rect> <!-- [ldio] generated by https://loading.io/ --></svg>
                </template>
              </button>
            </form>

          </div>
        </div>
      </div>
    </div>
  </div>  
</template>

<script>
import EventBus from '../../eventBus.js';
export default {
  data() {
    return {
      form: {
        title: "",
        description: "",
        subject: "",
      },
      subjects: [],
      theErrors: [],
      loading: false,
    };
  },

  mounted() {
    this.getSubjects();
  },

  methods: {
    async getSubjects() {
      let response = await axios.get("/api/subjects");
      if (response.status === 200) {
        this.subjects = response.data;

        console.log(response.data);
      }
    },

    async store() {
      try {
        this.loading = true;
        EventBus.$emit('loaderOverlay', true);
        let response = await axios.post( "/api/notes/create-new-note", this.form );
        if (response.status === 200) {
          
          this.loading = false;
          EventBus.$emit('loaderOverlay', false);

          this.form.title = "";
          this.form.description = "";
          this.form.subject = "";
          this.theErrors = [];
          this.$toasted.show(response.data.message, {
              position: 'top-center',
              duration: 3000,
              type: 'success',
              icon: 'done',
          });
        }
      } catch (e) {
        this.loading = false;
        EventBus.$emit('loaderOverlay', false);
        this.theErrors = e.response.data.errors;
        this.$toasted.show('Something went wrong....', {
              position: 'top-center',
              duration: 3000,
              type: 'error',
              icon: 'warning', 
          });
      }
    },
  },
};
</script>

<style>
</style>